expense.debug-enabled=true
expense.range-high=500
expense.range-low=100

# creating messages
expense.debug-message= Range [${expense.range-low}, ${expense.range-high}]

# manage profiles, for example dev
%dev.expense.range-low=10

%qa.expense.range-low=321
%qa2.expense.range-low=322

#if there is any env file, that will have more priority due to precedencia
